# This is a basic workflow to help you get started with Actions

name: deploy app to server
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # 切换分支
      - name: Checkout
        uses: actions/checkout@master
      # 下载 git submodule
      - uses: srt32/git-actions@v0.0.3
        with:
          args: git submodule update --init --recursive
      # 使用 node:12
      - name: use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12
      # 安装依赖
      - name: yarn
        run: |
          yarn
        env:
          CI: true
      # 构建
      - name: yarn docs:build
        run: |
          yarn docs:build
        env:
          CI: true

      # 部署
      - name: Deploy
        uses: easingthemes/ssh-deploy@v2.0.7
        env:
          SSH_PRIVATE_KEY: ${{ secrets.ACCESS_TOKEN }}
          # 删除服务器上目录里所有文件
          ARGS: "-avz --delete"
          # 项目 build 后静态文件位置
          SOURCE: "docs/.vuepress/dist"
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_PORT: ${{ secrets.REMOTE_PORT }} 
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          TARGET: ${{ secrets.TARGET }}
